services:
  dev-db:
    image: postgres:14
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: uscor
      POSTGRES_PASSWORD: uscor_pwd
      POSTGRES_DB: uscor_db
    networks:
      - freecodecamp

networks:
  freecodecamp:
    driver: bridge
